#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/upgrades-lab-agent-remote
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Upgrades.Lab.Agent.Remote.REST)
osgi.jaxrs.resource=true