dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.test", version: "default"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.test.integration", version: "default"
	testIntegrationImplementation project(":apps:upgrades-lab:upgrades-lab-agent-remote-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}