/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.upgrades.lab.agent.remote.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.upgrades.lab.agent.remote.model.UpgradeRun;
import com.liferay.upgrades.lab.agent.remote.service.UpgradeRunLocalService;
import com.liferay.upgrades.lab.agent.remote.service.persistence.UpgradeRunPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the upgrade run local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.upgrades.lab.agent.remote.service.impl.UpgradeRunLocalServiceImpl}.
 * </p>
 *
 * @author Albert Gomes Cabral
 * @see com.liferay.upgrades.lab.agent.remote.service.impl.UpgradeRunLocalServiceImpl
 * @generated
 */
public abstract class UpgradeRunLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, UpgradeRunLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UpgradeRunLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.upgrades.lab.agent.remote.service.UpgradeRunLocalServiceUtil</code>.
	 */

	/**
	 * Adds the upgrade run to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UpgradeRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param upgradeRun the upgrade run
	 * @return the upgrade run that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UpgradeRun addUpgradeRun(UpgradeRun upgradeRun) {
		upgradeRun.setNew(true);

		return upgradeRunPersistence.update(upgradeRun);
	}

	/**
	 * Creates a new upgrade run with the primary key. Does not add the upgrade run to the database.
	 *
	 * @param upgradeRunId the primary key for the new upgrade run
	 * @return the new upgrade run
	 */
	@Override
	@Transactional(enabled = false)
	public UpgradeRun createUpgradeRun(long upgradeRunId) {
		return upgradeRunPersistence.create(upgradeRunId);
	}

	/**
	 * Deletes the upgrade run with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UpgradeRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param upgradeRunId the primary key of the upgrade run
	 * @return the upgrade run that was removed
	 * @throws PortalException if a upgrade run with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UpgradeRun deleteUpgradeRun(long upgradeRunId)
		throws PortalException {

		return upgradeRunPersistence.remove(upgradeRunId);
	}

	/**
	 * Deletes the upgrade run from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UpgradeRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param upgradeRun the upgrade run
	 * @return the upgrade run that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UpgradeRun deleteUpgradeRun(UpgradeRun upgradeRun) {
		return upgradeRunPersistence.remove(upgradeRun);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return upgradeRunPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UpgradeRun.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return upgradeRunPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.upgrades.lab.agent.remote.model.impl.UpgradeRunModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return upgradeRunPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.upgrades.lab.agent.remote.model.impl.UpgradeRunModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return upgradeRunPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return upgradeRunPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return upgradeRunPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UpgradeRun fetchUpgradeRun(long upgradeRunId) {
		return upgradeRunPersistence.fetchByPrimaryKey(upgradeRunId);
	}

	/**
	 * Returns the upgrade run with the matching UUID and company.
	 *
	 * @param uuid the upgrade run's UUID
	 * @param companyId the primary key of the company
	 * @return the matching upgrade run, or <code>null</code> if a matching upgrade run could not be found
	 */
	@Override
	public UpgradeRun fetchUpgradeRunByUuidAndCompanyId(
		String uuid, long companyId) {

		return upgradeRunPersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	@Override
	public UpgradeRun fetchUpgradeRunByExternalReferenceCode(
		String externalReferenceCode, long companyId) {

		return upgradeRunPersistence.fetchByERC_C(
			externalReferenceCode, companyId);
	}

	@Override
	public UpgradeRun getUpgradeRunByExternalReferenceCode(
			String externalReferenceCode, long companyId)
		throws PortalException {

		return upgradeRunPersistence.findByERC_C(
			externalReferenceCode, companyId);
	}

	/**
	 * Returns the upgrade run with the primary key.
	 *
	 * @param upgradeRunId the primary key of the upgrade run
	 * @return the upgrade run
	 * @throws PortalException if a upgrade run with the primary key could not be found
	 */
	@Override
	public UpgradeRun getUpgradeRun(long upgradeRunId) throws PortalException {
		return upgradeRunPersistence.findByPrimaryKey(upgradeRunId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(upgradeRunLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UpgradeRun.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("upgradeRunId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			upgradeRunLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(UpgradeRun.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"upgradeRunId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(upgradeRunLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(UpgradeRun.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("upgradeRunId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<UpgradeRun>() {

				@Override
				public void performAction(UpgradeRun upgradeRun)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, upgradeRun);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(UpgradeRun.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return upgradeRunPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement UpgradeRunLocalServiceImpl#deleteUpgradeRun(UpgradeRun) to avoid orphaned data");
		}

		return upgradeRunLocalService.deleteUpgradeRun(
			(UpgradeRun)persistedModel);
	}

	@Override
	public BasePersistence<UpgradeRun> getBasePersistence() {
		return upgradeRunPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return upgradeRunPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the upgrade run with the matching UUID and company.
	 *
	 * @param uuid the upgrade run's UUID
	 * @param companyId the primary key of the company
	 * @return the matching upgrade run
	 * @throws PortalException if a matching upgrade run could not be found
	 */
	@Override
	public UpgradeRun getUpgradeRunByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return upgradeRunPersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the upgrade runs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.upgrades.lab.agent.remote.model.impl.UpgradeRunModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of upgrade runs
	 * @param end the upper bound of the range of upgrade runs (not inclusive)
	 * @return the range of upgrade runs
	 */
	@Override
	public List<UpgradeRun> getUpgradeRuns(int start, int end) {
		return upgradeRunPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of upgrade runs.
	 *
	 * @return the number of upgrade runs
	 */
	@Override
	public int getUpgradeRunsCount() {
		return upgradeRunPersistence.countAll();
	}

	/**
	 * Updates the upgrade run in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UpgradeRunLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param upgradeRun the upgrade run
	 * @return the upgrade run that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UpgradeRun updateUpgradeRun(UpgradeRun upgradeRun) {
		return upgradeRunPersistence.update(upgradeRun);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			UpgradeRunLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		upgradeRunLocalService = (UpgradeRunLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UpgradeRunLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UpgradeRun.class;
	}

	protected String getModelClassName() {
		return UpgradeRun.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = upgradeRunPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected UpgradeRunLocalService upgradeRunLocalService;

	@Reference
	protected UpgradeRunPersistence upgradeRunPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		UpgradeRunLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:1805975758