/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.upgrades.lab.agent.remote.model.impl;

import com.liferay.upgrades.lab.agent.remote.model.UpgradeRun;
import com.liferay.upgrades.lab.agent.remote.service.UpgradeRunLocalServiceUtil;

/**
 * The extended model base implementation for the UpgradeRun service. Represents a row in the &quot;Upgrades_UpgradeRun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpgradeRunImpl}.
 * </p>
 *
 * @author Albert Gomes Cabral
 * @see UpgradeRunImpl
 * @see UpgradeRun
 * @generated
 */
public abstract class UpgradeRunBaseImpl
	extends UpgradeRunModelImpl implements UpgradeRun {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a upgrade run model instance should use the <code>UpgradeRun</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UpgradeRunLocalServiceUtil.addUpgradeRun(this);
		}
		else {
			UpgradeRunLocalServiceUtil.updateUpgradeRun(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1759863757