/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.upgrades.lab.agent.remote.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.upgrades.lab.agent.remote.model.UpgradeRun;
import com.liferay.upgrades.lab.agent.remote.model.UpgradeRunModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UpgradeRun service. Represents a row in the &quot;Upgrades_UpgradeRun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UpgradeRunModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UpgradeRunImpl}.
 * </p>
 *
 * @author Albert Gomes Cabral
 * @see UpgradeRunImpl
 * @generated
 */
public class UpgradeRunModelImpl
	extends BaseModelImpl<UpgradeRun> implements UpgradeRunModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a upgrade run model instance should use the <code>UpgradeRun</code> interface instead.
	 */
	public static final String TABLE_NAME = "Upgrades_UpgradeRun";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"externalReferenceCode", Types.VARCHAR},
		{"upgradeRunId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"branch", Types.VARCHAR}, {"credentialKeyReference", Types.VARCHAR},
		{"customerName", Types.VARCHAR}, {"dbTargetType", Types.VARCHAR},
		{"dbTargetVersion", Types.VARCHAR}, {"endDate", Types.TIMESTAMP},
		{"nodeVersion", Types.VARCHAR}, {"pullRequestURL", Types.VARCHAR},
		{"repositoryURL", Types.VARCHAR}, {"resultBranch", Types.VARCHAR},
		{"searchVersion", Types.VARCHAR}, {"startDate", Types.TIMESTAMP},
		{"targetRelease", Types.VARCHAR},
		{"upgradeSourceVersion", Types.VARCHAR},
		{"upgradeTargetJavaVersion", Types.VARCHAR},
		{"workspacePath", Types.VARCHAR}, {"status", Types.INTEGER},
		{"statusMessage", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("upgradeRunId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("branch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("credentialKeyReference", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("customerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dbTargetType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dbTargetVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nodeVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pullRequestURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("repositoryURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resultBranch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("searchVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("targetRelease", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("upgradeSourceVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("upgradeTargetJavaVersion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workspacePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusMessage", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Upgrades_UpgradeRun (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,upgradeRunId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,branch VARCHAR(255) null,credentialKeyReference VARCHAR(255) null,customerName VARCHAR(75) null,dbTargetType VARCHAR(75) null,dbTargetVersion VARCHAR(75) null,endDate DATE null,nodeVersion VARCHAR(75) null,pullRequestURL VARCHAR(255) null,repositoryURL VARCHAR(255) null,resultBranch VARCHAR(255) null,searchVersion VARCHAR(75) null,startDate DATE null,targetRelease VARCHAR(75) null,upgradeSourceVersion VARCHAR(75) null,upgradeTargetJavaVersion VARCHAR(75) null,workspacePath STRING null,status INTEGER,statusMessage TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table Upgrades_UpgradeRun";

	public static final String ENTITY_ALIAS = "upgradeRun";

	public static final String ORDER_BY_JPQL =
		" ORDER BY upgradeRun.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Upgrades_UpgradeRun.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UpgradeRunModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _upgradeRunId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUpgradeRunId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _upgradeRunId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UpgradeRun.class;
	}

	@Override
	public String getModelClassName() {
		return UpgradeRun.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UpgradeRun, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UpgradeRun, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UpgradeRun, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((UpgradeRun)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UpgradeRun, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UpgradeRun, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UpgradeRun)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UpgradeRun, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UpgradeRun, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<UpgradeRun, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<UpgradeRun, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<UpgradeRun, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", UpgradeRun::getMvccVersion);
			attributeGetterFunctions.put("uuid", UpgradeRun::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode", UpgradeRun::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"upgradeRunId", UpgradeRun::getUpgradeRunId);
			attributeGetterFunctions.put("companyId", UpgradeRun::getCompanyId);
			attributeGetterFunctions.put("userId", UpgradeRun::getUserId);
			attributeGetterFunctions.put("userName", UpgradeRun::getUserName);
			attributeGetterFunctions.put(
				"createDate", UpgradeRun::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", UpgradeRun::getModifiedDate);
			attributeGetterFunctions.put("branch", UpgradeRun::getBranch);
			attributeGetterFunctions.put(
				"credentialKeyReference",
				UpgradeRun::getCredentialKeyReference);
			attributeGetterFunctions.put(
				"customerName", UpgradeRun::getCustomerName);
			attributeGetterFunctions.put(
				"dbTargetType", UpgradeRun::getDbTargetType);
			attributeGetterFunctions.put(
				"dbTargetVersion", UpgradeRun::getDbTargetVersion);
			attributeGetterFunctions.put("endDate", UpgradeRun::getEndDate);
			attributeGetterFunctions.put(
				"nodeVersion", UpgradeRun::getNodeVersion);
			attributeGetterFunctions.put(
				"pullRequestURL", UpgradeRun::getPullRequestURL);
			attributeGetterFunctions.put(
				"repositoryURL", UpgradeRun::getRepositoryURL);
			attributeGetterFunctions.put(
				"resultBranch", UpgradeRun::getResultBranch);
			attributeGetterFunctions.put(
				"searchVersion", UpgradeRun::getSearchVersion);
			attributeGetterFunctions.put("startDate", UpgradeRun::getStartDate);
			attributeGetterFunctions.put(
				"targetRelease", UpgradeRun::getTargetRelease);
			attributeGetterFunctions.put(
				"upgradeSourceVersion", UpgradeRun::getUpgradeSourceVersion);
			attributeGetterFunctions.put(
				"upgradeTargetJavaVersion",
				UpgradeRun::getUpgradeTargetJavaVersion);
			attributeGetterFunctions.put(
				"workspacePath", UpgradeRun::getWorkspacePath);
			attributeGetterFunctions.put("status", UpgradeRun::getStatus);
			attributeGetterFunctions.put(
				"statusMessage", UpgradeRun::getStatusMessage);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<UpgradeRun, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UpgradeRun, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<UpgradeRun, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<UpgradeRun, Long>)UpgradeRun::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<UpgradeRun, String>)UpgradeRun::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<UpgradeRun, String>)
					UpgradeRun::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"upgradeRunId",
				(BiConsumer<UpgradeRun, Long>)UpgradeRun::setUpgradeRunId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<UpgradeRun, Long>)UpgradeRun::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<UpgradeRun, Long>)UpgradeRun::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<UpgradeRun, Date>)UpgradeRun::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<UpgradeRun, Date>)UpgradeRun::setModifiedDate);
			attributeSetterBiConsumers.put(
				"branch",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setBranch);
			attributeSetterBiConsumers.put(
				"credentialKeyReference",
				(BiConsumer<UpgradeRun, String>)
					UpgradeRun::setCredentialKeyReference);
			attributeSetterBiConsumers.put(
				"customerName",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setCustomerName);
			attributeSetterBiConsumers.put(
				"dbTargetType",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setDbTargetType);
			attributeSetterBiConsumers.put(
				"dbTargetVersion",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setDbTargetVersion);
			attributeSetterBiConsumers.put(
				"endDate",
				(BiConsumer<UpgradeRun, Date>)UpgradeRun::setEndDate);
			attributeSetterBiConsumers.put(
				"nodeVersion",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setNodeVersion);
			attributeSetterBiConsumers.put(
				"pullRequestURL",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setPullRequestURL);
			attributeSetterBiConsumers.put(
				"repositoryURL",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setRepositoryURL);
			attributeSetterBiConsumers.put(
				"resultBranch",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setResultBranch);
			attributeSetterBiConsumers.put(
				"searchVersion",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setSearchVersion);
			attributeSetterBiConsumers.put(
				"startDate",
				(BiConsumer<UpgradeRun, Date>)UpgradeRun::setStartDate);
			attributeSetterBiConsumers.put(
				"targetRelease",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setTargetRelease);
			attributeSetterBiConsumers.put(
				"upgradeSourceVersion",
				(BiConsumer<UpgradeRun, String>)
					UpgradeRun::setUpgradeSourceVersion);
			attributeSetterBiConsumers.put(
				"upgradeTargetJavaVersion",
				(BiConsumer<UpgradeRun, String>)
					UpgradeRun::setUpgradeTargetJavaVersion);
			attributeSetterBiConsumers.put(
				"workspacePath",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setWorkspacePath);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<UpgradeRun, Integer>)UpgradeRun::setStatus);
			attributeSetterBiConsumers.put(
				"statusMessage",
				(BiConsumer<UpgradeRun, String>)UpgradeRun::setStatusMessage);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@Override
	public long getUpgradeRunId() {
		return _upgradeRunId;
	}

	@Override
	public void setUpgradeRunId(long upgradeRunId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_upgradeRunId = upgradeRunId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getBranch() {
		if (_branch == null) {
			return "";
		}
		else {
			return _branch;
		}
	}

	@Override
	public void setBranch(String branch) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_branch = branch;
	}

	@Override
	public String getCredentialKeyReference() {
		if (_credentialKeyReference == null) {
			return "";
		}
		else {
			return _credentialKeyReference;
		}
	}

	@Override
	public void setCredentialKeyReference(String credentialKeyReference) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_credentialKeyReference = credentialKeyReference;
	}

	@Override
	public String getCustomerName() {
		if (_customerName == null) {
			return "";
		}
		else {
			return _customerName;
		}
	}

	@Override
	public void setCustomerName(String customerName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_customerName = customerName;
	}

	@Override
	public String getDbTargetType() {
		if (_dbTargetType == null) {
			return "";
		}
		else {
			return _dbTargetType;
		}
	}

	@Override
	public void setDbTargetType(String dbTargetType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dbTargetType = dbTargetType;
	}

	@Override
	public String getDbTargetVersion() {
		if (_dbTargetVersion == null) {
			return "";
		}
		else {
			return _dbTargetVersion;
		}
	}

	@Override
	public void setDbTargetVersion(String dbTargetVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dbTargetVersion = dbTargetVersion;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@Override
	public String getNodeVersion() {
		if (_nodeVersion == null) {
			return "";
		}
		else {
			return _nodeVersion;
		}
	}

	@Override
	public void setNodeVersion(String nodeVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nodeVersion = nodeVersion;
	}

	@Override
	public String getPullRequestURL() {
		if (_pullRequestURL == null) {
			return "";
		}
		else {
			return _pullRequestURL;
		}
	}

	@Override
	public void setPullRequestURL(String pullRequestURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pullRequestURL = pullRequestURL;
	}

	@Override
	public String getRepositoryURL() {
		if (_repositoryURL == null) {
			return "";
		}
		else {
			return _repositoryURL;
		}
	}

	@Override
	public void setRepositoryURL(String repositoryURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_repositoryURL = repositoryURL;
	}

	@Override
	public String getResultBranch() {
		if (_resultBranch == null) {
			return "";
		}
		else {
			return _resultBranch;
		}
	}

	@Override
	public void setResultBranch(String resultBranch) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resultBranch = resultBranch;
	}

	@Override
	public String getSearchVersion() {
		if (_searchVersion == null) {
			return "";
		}
		else {
			return _searchVersion;
		}
	}

	@Override
	public void setSearchVersion(String searchVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_searchVersion = searchVersion;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@Override
	public String getTargetRelease() {
		if (_targetRelease == null) {
			return "";
		}
		else {
			return _targetRelease;
		}
	}

	@Override
	public void setTargetRelease(String targetRelease) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_targetRelease = targetRelease;
	}

	@Override
	public String getUpgradeSourceVersion() {
		if (_upgradeSourceVersion == null) {
			return "";
		}
		else {
			return _upgradeSourceVersion;
		}
	}

	@Override
	public void setUpgradeSourceVersion(String upgradeSourceVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_upgradeSourceVersion = upgradeSourceVersion;
	}

	@Override
	public String getUpgradeTargetJavaVersion() {
		if (_upgradeTargetJavaVersion == null) {
			return "";
		}
		else {
			return _upgradeTargetJavaVersion;
		}
	}

	@Override
	public void setUpgradeTargetJavaVersion(String upgradeTargetJavaVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_upgradeTargetJavaVersion = upgradeTargetJavaVersion;
	}

	@Override
	public String getWorkspacePath() {
		if (_workspacePath == null) {
			return "";
		}
		else {
			return _workspacePath;
		}
	}

	@Override
	public void setWorkspacePath(String workspacePath) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workspacePath = workspacePath;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public String getStatusMessage() {
		return _statusMessage;
	}

	@Override
	public void setStatusMessage(String statusMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusMessage = statusMessage;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(UpgradeRun.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), UpgradeRun.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UpgradeRun toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UpgradeRun>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UpgradeRunImpl upgradeRunImpl = new UpgradeRunImpl();

		upgradeRunImpl.setMvccVersion(getMvccVersion());
		upgradeRunImpl.setUuid(getUuid());
		upgradeRunImpl.setExternalReferenceCode(getExternalReferenceCode());
		upgradeRunImpl.setUpgradeRunId(getUpgradeRunId());
		upgradeRunImpl.setCompanyId(getCompanyId());
		upgradeRunImpl.setUserId(getUserId());
		upgradeRunImpl.setUserName(getUserName());
		upgradeRunImpl.setCreateDate(getCreateDate());
		upgradeRunImpl.setModifiedDate(getModifiedDate());
		upgradeRunImpl.setBranch(getBranch());
		upgradeRunImpl.setCredentialKeyReference(getCredentialKeyReference());
		upgradeRunImpl.setCustomerName(getCustomerName());
		upgradeRunImpl.setDbTargetType(getDbTargetType());
		upgradeRunImpl.setDbTargetVersion(getDbTargetVersion());
		upgradeRunImpl.setEndDate(getEndDate());
		upgradeRunImpl.setNodeVersion(getNodeVersion());
		upgradeRunImpl.setPullRequestURL(getPullRequestURL());
		upgradeRunImpl.setRepositoryURL(getRepositoryURL());
		upgradeRunImpl.setResultBranch(getResultBranch());
		upgradeRunImpl.setSearchVersion(getSearchVersion());
		upgradeRunImpl.setStartDate(getStartDate());
		upgradeRunImpl.setTargetRelease(getTargetRelease());
		upgradeRunImpl.setUpgradeSourceVersion(getUpgradeSourceVersion());
		upgradeRunImpl.setUpgradeTargetJavaVersion(
			getUpgradeTargetJavaVersion());
		upgradeRunImpl.setWorkspacePath(getWorkspacePath());
		upgradeRunImpl.setStatus(getStatus());
		upgradeRunImpl.setStatusMessage(getStatusMessage());

		upgradeRunImpl.resetOriginalValues();

		return upgradeRunImpl;
	}

	@Override
	public UpgradeRun cloneWithOriginalValues() {
		UpgradeRunImpl upgradeRunImpl = new UpgradeRunImpl();

		upgradeRunImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		upgradeRunImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		upgradeRunImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		upgradeRunImpl.setUpgradeRunId(
			this.<Long>getColumnOriginalValue("upgradeRunId"));
		upgradeRunImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		upgradeRunImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		upgradeRunImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		upgradeRunImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		upgradeRunImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		upgradeRunImpl.setBranch(this.<String>getColumnOriginalValue("branch"));
		upgradeRunImpl.setCredentialKeyReference(
			this.<String>getColumnOriginalValue("credentialKeyReference"));
		upgradeRunImpl.setCustomerName(
			this.<String>getColumnOriginalValue("customerName"));
		upgradeRunImpl.setDbTargetType(
			this.<String>getColumnOriginalValue("dbTargetType"));
		upgradeRunImpl.setDbTargetVersion(
			this.<String>getColumnOriginalValue("dbTargetVersion"));
		upgradeRunImpl.setEndDate(this.<Date>getColumnOriginalValue("endDate"));
		upgradeRunImpl.setNodeVersion(
			this.<String>getColumnOriginalValue("nodeVersion"));
		upgradeRunImpl.setPullRequestURL(
			this.<String>getColumnOriginalValue("pullRequestURL"));
		upgradeRunImpl.setRepositoryURL(
			this.<String>getColumnOriginalValue("repositoryURL"));
		upgradeRunImpl.setResultBranch(
			this.<String>getColumnOriginalValue("resultBranch"));
		upgradeRunImpl.setSearchVersion(
			this.<String>getColumnOriginalValue("searchVersion"));
		upgradeRunImpl.setStartDate(
			this.<Date>getColumnOriginalValue("startDate"));
		upgradeRunImpl.setTargetRelease(
			this.<String>getColumnOriginalValue("targetRelease"));
		upgradeRunImpl.setUpgradeSourceVersion(
			this.<String>getColumnOriginalValue("upgradeSourceVersion"));
		upgradeRunImpl.setUpgradeTargetJavaVersion(
			this.<String>getColumnOriginalValue("upgradeTargetJavaVersion"));
		upgradeRunImpl.setWorkspacePath(
			this.<String>getColumnOriginalValue("workspacePath"));
		upgradeRunImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		upgradeRunImpl.setStatusMessage(
			this.<String>getColumnOriginalValue("statusMessage"));

		return upgradeRunImpl;
	}

	@Override
	public int compareTo(UpgradeRun upgradeRun) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), upgradeRun.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UpgradeRun)) {
			return false;
		}

		UpgradeRun upgradeRun = (UpgradeRun)object;

		long primaryKey = upgradeRun.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UpgradeRun> toCacheModel() {
		UpgradeRunCacheModel upgradeRunCacheModel = new UpgradeRunCacheModel();

		upgradeRunCacheModel.mvccVersion = getMvccVersion();

		upgradeRunCacheModel.uuid = getUuid();

		String uuid = upgradeRunCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			upgradeRunCacheModel.uuid = null;
		}

		upgradeRunCacheModel.externalReferenceCode = getExternalReferenceCode();

		String externalReferenceCode =
			upgradeRunCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			upgradeRunCacheModel.externalReferenceCode = null;
		}

		upgradeRunCacheModel.upgradeRunId = getUpgradeRunId();

		upgradeRunCacheModel.companyId = getCompanyId();

		upgradeRunCacheModel.userId = getUserId();

		upgradeRunCacheModel.userName = getUserName();

		String userName = upgradeRunCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			upgradeRunCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			upgradeRunCacheModel.createDate = createDate.getTime();
		}
		else {
			upgradeRunCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			upgradeRunCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			upgradeRunCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		upgradeRunCacheModel.branch = getBranch();

		String branch = upgradeRunCacheModel.branch;

		if ((branch != null) && (branch.length() == 0)) {
			upgradeRunCacheModel.branch = null;
		}

		upgradeRunCacheModel.credentialKeyReference =
			getCredentialKeyReference();

		String credentialKeyReference =
			upgradeRunCacheModel.credentialKeyReference;

		if ((credentialKeyReference != null) &&
			(credentialKeyReference.length() == 0)) {

			upgradeRunCacheModel.credentialKeyReference = null;
		}

		upgradeRunCacheModel.customerName = getCustomerName();

		String customerName = upgradeRunCacheModel.customerName;

		if ((customerName != null) && (customerName.length() == 0)) {
			upgradeRunCacheModel.customerName = null;
		}

		upgradeRunCacheModel.dbTargetType = getDbTargetType();

		String dbTargetType = upgradeRunCacheModel.dbTargetType;

		if ((dbTargetType != null) && (dbTargetType.length() == 0)) {
			upgradeRunCacheModel.dbTargetType = null;
		}

		upgradeRunCacheModel.dbTargetVersion = getDbTargetVersion();

		String dbTargetVersion = upgradeRunCacheModel.dbTargetVersion;

		if ((dbTargetVersion != null) && (dbTargetVersion.length() == 0)) {
			upgradeRunCacheModel.dbTargetVersion = null;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			upgradeRunCacheModel.endDate = endDate.getTime();
		}
		else {
			upgradeRunCacheModel.endDate = Long.MIN_VALUE;
		}

		upgradeRunCacheModel.nodeVersion = getNodeVersion();

		String nodeVersion = upgradeRunCacheModel.nodeVersion;

		if ((nodeVersion != null) && (nodeVersion.length() == 0)) {
			upgradeRunCacheModel.nodeVersion = null;
		}

		upgradeRunCacheModel.pullRequestURL = getPullRequestURL();

		String pullRequestURL = upgradeRunCacheModel.pullRequestURL;

		if ((pullRequestURL != null) && (pullRequestURL.length() == 0)) {
			upgradeRunCacheModel.pullRequestURL = null;
		}

		upgradeRunCacheModel.repositoryURL = getRepositoryURL();

		String repositoryURL = upgradeRunCacheModel.repositoryURL;

		if ((repositoryURL != null) && (repositoryURL.length() == 0)) {
			upgradeRunCacheModel.repositoryURL = null;
		}

		upgradeRunCacheModel.resultBranch = getResultBranch();

		String resultBranch = upgradeRunCacheModel.resultBranch;

		if ((resultBranch != null) && (resultBranch.length() == 0)) {
			upgradeRunCacheModel.resultBranch = null;
		}

		upgradeRunCacheModel.searchVersion = getSearchVersion();

		String searchVersion = upgradeRunCacheModel.searchVersion;

		if ((searchVersion != null) && (searchVersion.length() == 0)) {
			upgradeRunCacheModel.searchVersion = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			upgradeRunCacheModel.startDate = startDate.getTime();
		}
		else {
			upgradeRunCacheModel.startDate = Long.MIN_VALUE;
		}

		upgradeRunCacheModel.targetRelease = getTargetRelease();

		String targetRelease = upgradeRunCacheModel.targetRelease;

		if ((targetRelease != null) && (targetRelease.length() == 0)) {
			upgradeRunCacheModel.targetRelease = null;
		}

		upgradeRunCacheModel.upgradeSourceVersion = getUpgradeSourceVersion();

		String upgradeSourceVersion = upgradeRunCacheModel.upgradeSourceVersion;

		if ((upgradeSourceVersion != null) &&
			(upgradeSourceVersion.length() == 0)) {

			upgradeRunCacheModel.upgradeSourceVersion = null;
		}

		upgradeRunCacheModel.upgradeTargetJavaVersion =
			getUpgradeTargetJavaVersion();

		String upgradeTargetJavaVersion =
			upgradeRunCacheModel.upgradeTargetJavaVersion;

		if ((upgradeTargetJavaVersion != null) &&
			(upgradeTargetJavaVersion.length() == 0)) {

			upgradeRunCacheModel.upgradeTargetJavaVersion = null;
		}

		upgradeRunCacheModel.workspacePath = getWorkspacePath();

		String workspacePath = upgradeRunCacheModel.workspacePath;

		if ((workspacePath != null) && (workspacePath.length() == 0)) {
			upgradeRunCacheModel.workspacePath = null;
		}

		upgradeRunCacheModel.status = getStatus();

		upgradeRunCacheModel.statusMessage = getStatusMessage();

		String statusMessage = upgradeRunCacheModel.statusMessage;

		if ((statusMessage != null) && (statusMessage.length() == 0)) {
			upgradeRunCacheModel.statusMessage = null;
		}

		return upgradeRunCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UpgradeRun, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UpgradeRun, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UpgradeRun, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UpgradeRun)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UpgradeRun>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UpgradeRun.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private String _externalReferenceCode;
	private long _upgradeRunId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _branch;
	private String _credentialKeyReference;
	private String _customerName;
	private String _dbTargetType;
	private String _dbTargetVersion;
	private Date _endDate;
	private String _nodeVersion;
	private String _pullRequestURL;
	private String _repositoryURL;
	private String _resultBranch;
	private String _searchVersion;
	private Date _startDate;
	private String _targetRelease;
	private String _upgradeSourceVersion;
	private String _upgradeTargetJavaVersion;
	private String _workspacePath;
	private int _status;
	private String _statusMessage;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<UpgradeRun, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UpgradeRun)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("upgradeRunId", _upgradeRunId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("branch", _branch);
		_columnOriginalValues.put(
			"credentialKeyReference", _credentialKeyReference);
		_columnOriginalValues.put("customerName", _customerName);
		_columnOriginalValues.put("dbTargetType", _dbTargetType);
		_columnOriginalValues.put("dbTargetVersion", _dbTargetVersion);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("nodeVersion", _nodeVersion);
		_columnOriginalValues.put("pullRequestURL", _pullRequestURL);
		_columnOriginalValues.put("repositoryURL", _repositoryURL);
		_columnOriginalValues.put("resultBranch", _resultBranch);
		_columnOriginalValues.put("searchVersion", _searchVersion);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("targetRelease", _targetRelease);
		_columnOriginalValues.put(
			"upgradeSourceVersion", _upgradeSourceVersion);
		_columnOriginalValues.put(
			"upgradeTargetJavaVersion", _upgradeTargetJavaVersion);
		_columnOriginalValues.put("workspacePath", _workspacePath);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusMessage", _statusMessage);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("externalReferenceCode", 4L);

		columnBitmasks.put("upgradeRunId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("branch", 512L);

		columnBitmasks.put("credentialKeyReference", 1024L);

		columnBitmasks.put("customerName", 2048L);

		columnBitmasks.put("dbTargetType", 4096L);

		columnBitmasks.put("dbTargetVersion", 8192L);

		columnBitmasks.put("endDate", 16384L);

		columnBitmasks.put("nodeVersion", 32768L);

		columnBitmasks.put("pullRequestURL", 65536L);

		columnBitmasks.put("repositoryURL", 131072L);

		columnBitmasks.put("resultBranch", 262144L);

		columnBitmasks.put("searchVersion", 524288L);

		columnBitmasks.put("startDate", 1048576L);

		columnBitmasks.put("targetRelease", 2097152L);

		columnBitmasks.put("upgradeSourceVersion", 4194304L);

		columnBitmasks.put("upgradeTargetJavaVersion", 8388608L);

		columnBitmasks.put("workspacePath", 16777216L);

		columnBitmasks.put("status", 33554432L);

		columnBitmasks.put("statusMessage", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UpgradeRun _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-553972885