/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.upgrades.lab.agent.remote.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UpgradeRun service. Represents a row in the &quot;Upgrades_UpgradeRun&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.upgrades.lab.agent.remote.model.impl.UpgradeRunModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.upgrades.lab.agent.remote.model.impl.UpgradeRunImpl</code>.
 * </p>
 *
 * @author Albert Gomes Cabral
 * @see UpgradeRun
 * @generated
 */
@ProviderType
public interface UpgradeRunModel
	extends BaseModel<UpgradeRun>, ExternalReferenceCodeModel, MVCCModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a upgrade run model instance should use the {@link UpgradeRun} interface instead.
	 */

	/**
	 * Returns the primary key of this upgrade run.
	 *
	 * @return the primary key of this upgrade run
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this upgrade run.
	 *
	 * @param primaryKey the primary key of this upgrade run
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this upgrade run.
	 *
	 * @return the mvcc version of this upgrade run
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this upgrade run.
	 *
	 * @param mvccVersion the mvcc version of this upgrade run
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this upgrade run.
	 *
	 * @return the uuid of this upgrade run
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this upgrade run.
	 *
	 * @param uuid the uuid of this upgrade run
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this upgrade run.
	 *
	 * @return the external reference code of this upgrade run
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this upgrade run.
	 *
	 * @param externalReferenceCode the external reference code of this upgrade run
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the upgrade run ID of this upgrade run.
	 *
	 * @return the upgrade run ID of this upgrade run
	 */
	public long getUpgradeRunId();

	/**
	 * Sets the upgrade run ID of this upgrade run.
	 *
	 * @param upgradeRunId the upgrade run ID of this upgrade run
	 */
	public void setUpgradeRunId(long upgradeRunId);

	/**
	 * Returns the company ID of this upgrade run.
	 *
	 * @return the company ID of this upgrade run
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this upgrade run.
	 *
	 * @param companyId the company ID of this upgrade run
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this upgrade run.
	 *
	 * @return the user ID of this upgrade run
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this upgrade run.
	 *
	 * @param userId the user ID of this upgrade run
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this upgrade run.
	 *
	 * @return the user uuid of this upgrade run
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this upgrade run.
	 *
	 * @param userUuid the user uuid of this upgrade run
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this upgrade run.
	 *
	 * @return the user name of this upgrade run
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this upgrade run.
	 *
	 * @param userName the user name of this upgrade run
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this upgrade run.
	 *
	 * @return the create date of this upgrade run
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this upgrade run.
	 *
	 * @param createDate the create date of this upgrade run
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this upgrade run.
	 *
	 * @return the modified date of this upgrade run
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this upgrade run.
	 *
	 * @param modifiedDate the modified date of this upgrade run
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the branch of this upgrade run.
	 *
	 * @return the branch of this upgrade run
	 */
	@AutoEscape
	public String getBranch();

	/**
	 * Sets the branch of this upgrade run.
	 *
	 * @param branch the branch of this upgrade run
	 */
	public void setBranch(String branch);

	/**
	 * Returns the credential key reference of this upgrade run.
	 *
	 * @return the credential key reference of this upgrade run
	 */
	@AutoEscape
	public String getCredentialKeyReference();

	/**
	 * Sets the credential key reference of this upgrade run.
	 *
	 * @param credentialKeyReference the credential key reference of this upgrade run
	 */
	public void setCredentialKeyReference(String credentialKeyReference);

	/**
	 * Returns the customer name of this upgrade run.
	 *
	 * @return the customer name of this upgrade run
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this upgrade run.
	 *
	 * @param customerName the customer name of this upgrade run
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the db target type of this upgrade run.
	 *
	 * @return the db target type of this upgrade run
	 */
	@AutoEscape
	public String getDbTargetType();

	/**
	 * Sets the db target type of this upgrade run.
	 *
	 * @param dbTargetType the db target type of this upgrade run
	 */
	public void setDbTargetType(String dbTargetType);

	/**
	 * Returns the db target version of this upgrade run.
	 *
	 * @return the db target version of this upgrade run
	 */
	@AutoEscape
	public String getDbTargetVersion();

	/**
	 * Sets the db target version of this upgrade run.
	 *
	 * @param dbTargetVersion the db target version of this upgrade run
	 */
	public void setDbTargetVersion(String dbTargetVersion);

	/**
	 * Returns the end date of this upgrade run.
	 *
	 * @return the end date of this upgrade run
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this upgrade run.
	 *
	 * @param endDate the end date of this upgrade run
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the node version of this upgrade run.
	 *
	 * @return the node version of this upgrade run
	 */
	@AutoEscape
	public String getNodeVersion();

	/**
	 * Sets the node version of this upgrade run.
	 *
	 * @param nodeVersion the node version of this upgrade run
	 */
	public void setNodeVersion(String nodeVersion);

	/**
	 * Returns the pull request url of this upgrade run.
	 *
	 * @return the pull request url of this upgrade run
	 */
	@AutoEscape
	public String getPullRequestURL();

	/**
	 * Sets the pull request url of this upgrade run.
	 *
	 * @param pullRequestURL the pull request url of this upgrade run
	 */
	public void setPullRequestURL(String pullRequestURL);

	/**
	 * Returns the repository url of this upgrade run.
	 *
	 * @return the repository url of this upgrade run
	 */
	@AutoEscape
	public String getRepositoryURL();

	/**
	 * Sets the repository url of this upgrade run.
	 *
	 * @param repositoryURL the repository url of this upgrade run
	 */
	public void setRepositoryURL(String repositoryURL);

	/**
	 * Returns the result branch of this upgrade run.
	 *
	 * @return the result branch of this upgrade run
	 */
	@AutoEscape
	public String getResultBranch();

	/**
	 * Sets the result branch of this upgrade run.
	 *
	 * @param resultBranch the result branch of this upgrade run
	 */
	public void setResultBranch(String resultBranch);

	/**
	 * Returns the search version of this upgrade run.
	 *
	 * @return the search version of this upgrade run
	 */
	@AutoEscape
	public String getSearchVersion();

	/**
	 * Sets the search version of this upgrade run.
	 *
	 * @param searchVersion the search version of this upgrade run
	 */
	public void setSearchVersion(String searchVersion);

	/**
	 * Returns the start date of this upgrade run.
	 *
	 * @return the start date of this upgrade run
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this upgrade run.
	 *
	 * @param startDate the start date of this upgrade run
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the target release of this upgrade run.
	 *
	 * @return the target release of this upgrade run
	 */
	@AutoEscape
	public String getTargetRelease();

	/**
	 * Sets the target release of this upgrade run.
	 *
	 * @param targetRelease the target release of this upgrade run
	 */
	public void setTargetRelease(String targetRelease);

	/**
	 * Returns the upgrade source version of this upgrade run.
	 *
	 * @return the upgrade source version of this upgrade run
	 */
	@AutoEscape
	public String getUpgradeSourceVersion();

	/**
	 * Sets the upgrade source version of this upgrade run.
	 *
	 * @param upgradeSourceVersion the upgrade source version of this upgrade run
	 */
	public void setUpgradeSourceVersion(String upgradeSourceVersion);

	/**
	 * Returns the upgrade target java version of this upgrade run.
	 *
	 * @return the upgrade target java version of this upgrade run
	 */
	@AutoEscape
	public String getUpgradeTargetJavaVersion();

	/**
	 * Sets the upgrade target java version of this upgrade run.
	 *
	 * @param upgradeTargetJavaVersion the upgrade target java version of this upgrade run
	 */
	public void setUpgradeTargetJavaVersion(String upgradeTargetJavaVersion);

	/**
	 * Returns the workspace path of this upgrade run.
	 *
	 * @return the workspace path of this upgrade run
	 */
	@AutoEscape
	public String getWorkspacePath();

	/**
	 * Sets the workspace path of this upgrade run.
	 *
	 * @param workspacePath the workspace path of this upgrade run
	 */
	public void setWorkspacePath(String workspacePath);

	/**
	 * Returns the status of this upgrade run.
	 *
	 * @return the status of this upgrade run
	 */
	public int getStatus();

	/**
	 * Sets the status of this upgrade run.
	 *
	 * @param status the status of this upgrade run
	 */
	public void setStatus(int status);

	/**
	 * Returns the status message of this upgrade run.
	 *
	 * @return the status message of this upgrade run
	 */
	@AutoEscape
	public String getStatusMessage();

	/**
	 * Sets the status message of this upgrade run.
	 *
	 * @param statusMessage the status message of this upgrade run
	 */
	public void setStatusMessage(String statusMessage);

	@Override
	public UpgradeRun cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1793981360