create table UpgradeRun (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	upgradeRunId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	branch VARCHAR(255) null,
	credentialKeyReference VARCHAR(255) null,
	customerName VARCHAR(75) null,
	dbTargetType VARCHAR(75) null,
	dbTargetVersion VARCHAR(75) null,
	endDate DATE null,
	firstPhase INTEGER,
	licensePath VARCHAR(255) null,
	nodeVersion VARCHAR(75) null,
	pullRequestURL VARCHAR(255) null,
	repositoryURL VARCHAR(255) null,
	resultBranch VARCHAR(255) null,
	searchVersion VARCHAR(75) null,
	startDate DATE null,
	upgradeSourceVersion VARCHAR(75) null,
	upgradeTargetJavaVersion VARCHAR(75) null,
	upgradeTargetVersion VARCHAR(75) null,
	workspacePath STRING null,
	status INTEGER,
	statusMessage TEXT null
);